#!/usr/bin/perl

$SCRIPT = "mk_env.sh";
$DOTS   = "dot-*";    # dot files
$ENVDIR = "env";

if( -e $SCRIPT){
    print STDERR "$SCRIPT exist\n";
#    exit 1;
}
open(LS, "/bin/ls $DOTS |") or die $!;

open(SCRIPT, ">$SCRIPT") or die $!;
print SCRIPT << "SCRIPT_HEADER";
#!/bin/sh
# This file is automatically generated by $0.

if [ \${HOME} != `pwd` ]; then
  echo "Run this script in \$HOME"
  exit 1
fi
SCRIPT_HEADER

while(<LS>){
    chomp;
    $dot_file = $_;
    $link     = $_;
    $link     =~ s/dot-/./;
    print SCRIPT << "SCRIPT";
if [ -e $link ] ; then
   echo "$link already exists"
else
   ln -s $ENVDIR/$dot_file $link;
fi

SCRIPT
}
