#!/bin/sh
# This file is automatically generated by ./mk-env.pl.

if [ ${HOME} != `pwd` ]; then
  echo "Run this script in $HOME"
  exit 1
fi
if [ -e .alias ] ; then
   echo ".alias already exists"
else
   ln -s env/dot-alias .alias;
fi

if [ -e .emacs ] ; then
   echo ".emacs already exists"
else
   ln -s env/dot-emacs .emacs;
fi

if [ -e .profile ] ; then
   echo ".profile already exists"
else
   ln -s env/dot-profile .profile;
fi

